---

- hosts: all
  become: yes
  pre_tasks:

  - name: update & upgrade server
    apt: 
      update_cache: yes
      upgrade: yes


- hosts: all
  become: true
  roles:
    - server_uptime

- hosts: all
  become: true
  become_user: root
  roles:
    - copy_file